### ISSUE TITLE
could you please help me check if there is any problem with my data set?

### ISSUE THREAD

**Issue by scially** [laxnpander/OpenREALM#23]
Hello, could you please help me check if there is any problem with my data set? Except the camera parameters and orbslam params, all the other parameters are default, but the orthophoto results are not good, thanks~

Datas Share URL:  
[https://drive.google.com/file/d/18cfaPikdErhAKo0jISpyOH6OYdfrY941/view?usp=sharing](https://drive.google.com/file/d/18cfaPikdErhAKo0jISpyOH6OYdfrY941/view?usp=sharing)
---
the camera config is
``` YAML
type: pinhole
# Frames per second
fps: 5
# Image size
width: 1368
height: 912
# Principal point
cx: 689.97
cy: 456.58
# Focal length
fx: 2010.848
fy: 1340.565
# Distortion
k1: -0.266511765417987
k2: 0.10617945434786
p1: 0.000195369051756418
p2: 0.00143753730138743
k3: -0.0285408159411354
```
the `orb_slam2_settings` is 
```YAML
type: ORB_SLAM2

resizing: 1.0

nrof_features: 2500

scale_factor: 1.2

n_pyr_levels: 8

ini_th_FAST: 15
min_th_FAST: 3

# Path to the vocabulary file for place recognition
path_vocabulary: /orb_slam2/ORBvoc.bin

```
### my ortho result:
![image](https://user-images.githubusercontent.com/22127608/85547657-afb90a80-b650-11ea-9977-b9163dd1d1f8.png)

**Comment by laxnpander** [comment]
@scially Hey hey, your dataset looks quite okay. Some things might need improvement:
- Try to fix the heading, at the turning points you have way too much movement. Orb slam is losing its tracking there and has a hard time to relocalize after that, resulting in some bad points and bad estimation quality in general. This should be an easy fix for the next dataset.
- Your frame rate is okay, but not overwhelming. If you want to get better data, you might consider flying slower or increase framerate. The tracking of the orb slam really needs **as little movement per frame as possible** 
- Your lens has a bit of fisheye, it seems to be okay but ideally it would be less. Usually you are not as flexible on the hardware, so I guess you can't improve that.

Unfortunately there is no magic algorithm to fix these issues with your dataset. My framework is at best as good as the orb slam, and it has a hard time with your data. Fixing the heading of the drone might already do the job.

Let me know if it helped and best regards,
Alex

**Comment by scially** [comment]
Thank you~ 
I followed your suggestion, replaced a new UAV, and re-photographed an area, DJI FC6310S camera, the first route mosaicing perfect, but when it turned to the second route, although it was still Tracking, the mosaicing was not good, is my lateral overlap too high?

New Datas Share URL:
[https://drive.google.com/file/d/1xahiNa0fA_pKFx8Dr47Oltq20gaBAh_2/view?usp=sharing](https://drive.google.com/file/d/1xahiNa0fA_pKFx8Dr47Oltq20gaBAh_2/view?usp=sharing)  

the camera config is
```YAML
type: pinhole
# Frames per second
fps: 10.0
# Image size
width: 1368
height: 912
# Principal point
cx: 684.0
cy: 456.0
# Focal length
fx: 1989.818
fy: 1326.545
# Distortion
k1: 0.000001
k2: 0
p1: 0.000001
p2: 0.000001
k3: 0
```
![图片](https://user-images.githubusercontent.com/22127608/86004570-1752c980-ba46-11ea-993f-66dd51b99aa8.png)
![图片](https://user-images.githubusercontent.com/22127608/86004654-2d608a00-ba46-11ea-9d75-fbd0c3e87715.png)
